version: 2

jobs:
    test:
        working_directory: ~/wp-plugin

        docker:
            - image: circleci/php:8.0.12

        steps:
            - checkout

            - restore_cache:
                name: 'dependencies | restore cache'
                keys:
                    - dependencies-{{ checksum "composer.lock" }}

            - run:
                name: 'dependencies | install composer'
                command: 'composer install --prefer-source --no-interaction'

            - save_cache:
                name: 'dependencies | save cache'
                key: dependencies-{{ checksum "composer.lock" }}
                paths:
                    - app/vendor

            - run:
                name: 'tests | Varying Vagrants Vagrant: lint vvv-custom.yml'
                command: 'composer yaml-lint'

            - run:
                name: 'tests | WP plugin: PHP Code Sniffer'
                command: 'composer phpcs'

            - run:
                name: 'tests | WP plugin: PHPStan'
                command: 'composer phpstan'

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
